In [1]:
# ── Libraries ──────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', '{:.2f}'.format)

print("✅ All libraries imported successfully")

✅ All libraries imported successfully

In [6]:
# ── Load dataset ────────────────────────────────────────
df = pd.read_csv('/Users/apple/Documents/GitHub/airline-revenue-management/flights_clean.csv')

print(f"✅ Dataset loaded successfully")
print(f"📊 Shape : {df.shape[0]} rows × {df.shape[1]} columns")

✅ Dataset loaded successfully
📊 Shape : 10683 rows × 12 columns

In [7]:
df.head(10)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Revenue
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,22/03/26 1:10,2h 50m,non-stop,No info,3897,3897
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,5:50,13:15,7h 25m,2 stops,No info,7662,7662
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,9:25,10/06/26 4:25,19h,2 stops,No info,13882,13882
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,6218
4,IndiGo,2019-03-24,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,13302
5,SpiceJet,2019-05-01,Kolkata,Banglore,CCU → BLR,9:00,11:25,2h 25m,non-stop,No info,3873,3873
6,Jet Airways,2019-06-09,Banglore,New Delhi,BLR → BOM → DEL,18:55,13/03/26 10:25,15h 30m,1 stop,In-flight meal not included,11087,11087
7,Jet Airways,2019-05-12,Banglore,New Delhi,BLR → BOM → DEL,8:00,02/03/26 5:05,21h 5m,1 stop,No info,22270,22270
8,Jet Airways,2019-03-24,Banglore,New Delhi,BLR → BOM → DEL,8:55,13/03/26 10:25,25h 30m,1 stop,In-flight meal not included,11087,11087
9,Multiple carriers,2019-05-01,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625,8625

In [8]:
# ── Preview data ────────────────────────────────────────
print("=" * 55)
print("FIRST 10 ROWS")
print("=" * 55)
df.head(10)

=======================================================
FIRST 10 ROWS
=======================================================

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Revenue
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,22/03/26 1:10,2h 50m,non-stop,No info,3897,3897
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,5:50,13:15,7h 25m,2 stops,No info,7662,7662
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,9:25,10/06/26 4:25,19h,2 stops,No info,13882,13882
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,6218
4,IndiGo,2019-03-24,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,13302
5,SpiceJet,2019-05-01,Kolkata,Banglore,CCU → BLR,9:00,11:25,2h 25m,non-stop,No info,3873,3873
6,Jet Airways,2019-06-09,Banglore,New Delhi,BLR → BOM → DEL,18:55,13/03/26 10:25,15h 30m,1 stop,In-flight meal not included,11087,11087
7,Jet Airways,2019-05-12,Banglore,New Delhi,BLR → BOM → DEL,8:00,02/03/26 5:05,21h 5m,1 stop,No info,22270,22270
8,Jet Airways,2019-03-24,Banglore,New Delhi,BLR → BOM → DEL,8:55,13/03/26 10:25,25h 30m,1 stop,In-flight meal not included,11087,11087
9,Multiple carriers,2019-05-01,Delhi,Cochin,DEL → BOM → COK,11:25,19:15,7h 50m,1 stop,No info,8625,8625

In [9]:
# ── Column info ─────────────────────────────────────────
print("=" * 55)
print("COLUMN NAMES AND DATA TYPES")
print("=" * 55)
print(df.dtypes)
print()
print(f"Total columns : {df.shape[1]}")

=======================================================
COLUMN NAMES AND DATA TYPES
=======================================================
Airline              str
Date_of_Journey      str
Source               str
Destination          str
Route                str
Dep_Time             str
Arrival_Time         str
Duration             str
Total_Stops          str
Additional_Info      str
Price              int64
Revenue            int64
dtype: object

Total columns : 12

In [10]:
# ── Fix Date_of_Journey ─────────────────────────────────
df['Date_of_Journey'] = pd.to_datetime(
    df['Date_of_Journey'], dayfirst=True)

# Extract useful features from date
df['journey_month']    = df['Date_of_Journey'].dt.month
df['journey_day']      = df['Date_of_Journey'].dt.day
df['journey_weekday']  = df['Date_of_Journey'].dt.dayofweek
df['journey_quarter']  = df['Date_of_Journey'].dt.quarter
df['month_name']       = df['Date_of_Journey'].dt.strftime('%b')

print("✅ Date_of_Journey fixed")
print(df[['Date_of_Journey','journey_month',
          'journey_day','month_name']].head(5))

✅ Date_of_Journey fixed
  Date_of_Journey  journey_month  journey_day month_name
0      2019-03-24              3           24        Mar
1      2019-05-01              5            1        May
2      2019-06-09              6            9        Jun
3      2019-05-12              5           12        May
4      2019-03-24              3           24        Mar

In [16]:
# ── Fix Dep_Time — same mixed format handler ────────────
def parse_dep_time(val):
    val = str(val).strip()
    
    # Try format 1: DD/MM/YY H:MM
    try:
        return pd.to_datetime(val, format='%d/%m/%y %H:%M')
    except:
        pass
    
    # Try format 2: HH:MM
    try:
        return pd.to_datetime(val, format='%H:%M')
    except:
        pass
    
    # Try format 3: H:MM AM/PM
    try:
        return pd.to_datetime(val, format='%I:%M %p')
    except:
        pass

    # Try format 4: DD/MM/YYYY H:MM
    try:
        return pd.to_datetime(val, format='%d/%m/%Y %H:%M')
    except:
        pass

    return pd.NaT

df['dep_datetime']    = df['Dep_Time'].apply(parse_dep_time)
df['dep_hour']        = df['dep_datetime'].dt.hour
df['dep_time_of_day'] = df['dep_hour'].apply(time_of_day)

total     = len(df)
parsed_ok = df['dep_hour'].notna().sum()
failed    = df['dep_hour'].isna().sum()

print("=" * 55)
print("DEP TIME PARSING RESULTS")
print("=" * 55)
print(f"Total rows          : {total:,}")
print(f"Parsed successfully : {parsed_ok:,}")
print(f"Failed (NaN)        : {failed:,}")
print(f"Success rate        : {parsed_ok/total*100:.1f}%")
print()
print(df[['Dep_Time','dep_hour','dep_time_of_day']].head(15))

if failed > 0:
    print(f"\n⚠️  Still failing — sample values:")
    print(df[df['dep_hour'].isna()]['Dep_Time']\
          .head(10).tolist())

=======================================================
DEP TIME PARSING RESULTS
=======================================================
Total rows          : 10,683
Parsed successfully : 10,683
Failed (NaN)        : 0
Success rate        : 100.0%

   Dep_Time  dep_hour dep_time_of_day
0     22:20        22           Night
1      5:50         5         Morning
2      9:25         9         Morning
3     18:05        18         Evening
4     16:50        16       Afternoon
5      9:00         9         Morning
6     18:55        18         Evening
7      8:00         8         Morning
8      8:55         8         Morning
9     11:25        11         Morning
10     9:45         9         Morning
11    20:20        20         Evening
12    11:40        11         Morning
13    21:10        21           Night
14    17:15        17         Evening

In [15]:
# ── Fix Arrival_Time — mixed format handler ─────────────
def parse_arrival_time(val):
    val = str(val).strip()
    
    # Try format 1: DD/MM/YY H:MM  e.g. "22/03/26 1:10"
    try:
        return pd.to_datetime(val, format='%d/%m/%y %H:%M')
    except:
        pass
    
    # Try format 2: HH:MM  e.g. "22:20" or "1:10"
    try:
        return pd.to_datetime(val, format='%H:%M')
    except:
        pass
    
    # Try format 3: H:MM AM/PM  e.g. "6:05 AM"
    try:
        return pd.to_datetime(val, format='%I:%M %p')
    except:
        pass

    # Try format 4: DD/MM/YYYY H:MM  e.g. "22/03/2026 1:10"
    try:
        return pd.to_datetime(val, format='%d/%m/%Y %H:%M')
    except:
        pass

    # If all fail return NaT
    return pd.NaT

# Apply to full column
df['arrival_datetime'] = df['Arrival_Time'].apply(parse_arrival_time)

# Extract hour
df['arrival_hour'] = df['arrival_datetime'].dt.hour

# Time of day category
def time_of_day(hour):
    if pd.isna(hour):
        return 'Unknown'
    elif 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

df['arrival_time_of_day'] = df['arrival_hour'].apply(time_of_day)

# Flag next day arrivals only where full date is available
df['next_day_arrival'] = (
    df['arrival_datetime'].dt.date > df['Date_of_Journey'].dt.date
).astype(int)

# Verification
total      = len(df)
parsed_ok  = df['arrival_hour'].notna().sum()
failed     = df['arrival_hour'].isna().sum()

print("=" * 55)
print("ARRIVAL TIME PARSING RESULTS")
print("=" * 55)
print(f"Total rows          : {total:,}")
print(f"Parsed successfully : {parsed_ok:,}")
print(f"Failed (NaN)        : {failed:,}")
print(f"Success rate        : {parsed_ok/total*100:.1f}%")
print()
print(df[['Arrival_Time','arrival_hour',
          'arrival_time_of_day',
          'next_day_arrival']].head(15))

# Show remaining failed values if any
if failed > 0:
    print(f"\n⚠️  Still failing — sample values:")
    print(df[df['arrival_hour'].isna()]['Arrival_Time']\
          .head(10).tolist())

=======================================================
ARRIVAL TIME PARSING RESULTS
=======================================================
Total rows          : 10,683
Parsed successfully : 10,683
Failed (NaN)        : 0
Success rate        : 100.0%

      Arrival_Time  arrival_hour arrival_time_of_day  next_day_arrival
0    22/03/26 1:10             1               Night                 1
1            13:15            13           Afternoon                 0
2    10/06/26 4:25             4               Night                 1
3            23:30            23               Night                 0
4            21:35            21               Night                 0
5            11:25            11             Morning                 0
6   13/03/26 10:25            10             Morning                 1
7    02/03/26 5:05             5             Morning                 1
8   13/03/26 10:25            10             Morning                 1
9            19:15            19             Evening                 0
10           23:00            23               Night                 0
11           22:55            22               Night                 0
12           13:55            13           Afternoon                 0
13   10/05/26 9:20             9             Morning                 1
14           19:50            19             Evening                 0

In [17]:
# ── Fix Duration ────────────────────────────────────────
def parse_duration(dur):
    dur = str(dur).strip()
    hours   = 0
    minutes = 0
    if 'h' in dur:
        hours = int(dur.split('h')[0].strip())
    if 'm' in dur:
        minutes = int(dur.split('m')[0].split()[-1].strip())
    return (hours * 60) + minutes

df['duration_mins'] = df['Duration'].apply(parse_duration)

# Sanity check — flag anything under 30 mins or over 600 mins
invalid_duration = df[
    (df['duration_mins'] < 30) |
    (df['duration_mins'] > 600)
]
print(f"⚠️  Suspicious duration rows : {len(invalid_duration)}")
print("✅ Duration fixed")
print(df[['Duration','duration_mins']].head(10))

⚠️  Suspicious duration rows : 4711
✅ Duration fixed
  Duration  duration_mins
0   2h 50m            170
1   7h 25m            445
2      19h           1140
3   5h 25m            325
4   4h 45m            285
5   2h 25m            145
6  15h 30m            930
7   21h 5m           1265
8  25h 30m           1530
9   7h 50m            470

In [24]:
# ── Fix Total_Stops — handle 1 NaN row ──────────────────
stops_map = {
    'non-stop' : 0,
    '1 stop'   : 1,
    '2 stops'  : 2,
    '3 stops'  : 3,
    '4 stops'  : 4
}

df['stops_clean'] = df['Total_Stops']\
    .str.strip()\
    .str.lower()\
    .map(stops_map)

# Fill the 1 missing row with median (most common sense approach)
median_stops = df['stops_clean'].median()
df['stops_clean'] = df['stops_clean'].fillna(median_stops)

# Convert to integer now that no NaN exists
df['stops_clean'] = df['stops_clean'].astype(int)

# Verify
print("=" * 55)
print("TOTAL STOPS — CLEAN")
print("=" * 55)
print(df['stops_clean'].value_counts().sort_index())
print()
print(f"Data type     : {df['stops_clean'].dtype}")
print(f"Missing values: {df['stops_clean'].isna().sum()}")
print()
print(df[['Total_Stops','stops_clean']].head(10))
print("✅ Total_Stops fully cleaned")

=======================================================
TOTAL STOPS — CLEAN
=======================================================
stops_clean
0    3491
1    5626
2    1520
3      45
4       1
Name: count, dtype: int64

Data type     : int64
Missing values: 0

  Total_Stops  stops_clean
0    non-stop            0
1     2 stops            2
2     2 stops            2
3      1 stop            1
4      1 stop            1
5    non-stop            0
6      1 stop            1
7      1 stop            1
8      1 stop            1
9      1 stop            1
✅ Total_Stops fully cleaned

In [25]:
# ── Full cleaning status check ───────────────────────────
print("=" * 55)
print("CLEANING STATUS — ALL COLUMNS")
print("=" * 55)

cols = {
    'Date_of_Journey' : 'datetime64[ns]',
    'dep_hour'        : 'int or float',
    'arrival_hour'    : 'int or float',
    'duration_mins'   : 'int or float',
    'stops_clean'     : 'int64',
    'Price'           : 'int64',
    'Revenue'         : 'int64'
}

for col, expected in cols.items():
    if col in df.columns:
        null_count = df[col].isna().sum()
        status = "✅" if null_count == 0 else f"⚠️  {null_count} nulls"
        print(f"{col:<22} | {str(df[col].dtype):<18} | {status}")

=======================================================
CLEANING STATUS — ALL COLUMNS
=======================================================
Date_of_Journey        | datetime64[us]     | ✅
dep_hour               | int32              | ✅
arrival_hour           | int32              | ✅
duration_mins          | int64              | ✅
stops_clean            | int64              | ✅
Price                  | int64              | ✅
Revenue                | int64              | ✅

In [26]:
# ── Final check ─────────────────────────────────────────
print("=" * 55)
print("COLUMN TYPES AFTER CLEANING")
print("=" * 55)

cols_to_check = [
    'Date_of_Journey', 'journey_month', 'journey_weekday',
    'dep_hour', 'dep_time_of_day',
    'arrival_hour', 'next_day_arrival',
    'duration_mins', 'stops_clean',
    'Price', 'Revenue'
]

for col in cols_to_check:
    if col in df.columns:
        print(f"{col:<22} : {str(df[col].dtype):<10} "
              f"| sample: {df[col].iloc[0]}")

=======================================================
COLUMN TYPES AFTER CLEANING
=======================================================
Date_of_Journey        : datetime64[us] | sample: 2019-03-24 00:00:00
journey_month          : int32      | sample: 3
journey_weekday        : int32      | sample: 6
dep_hour               : int32      | sample: 22
dep_time_of_day        : str        | sample: Night
arrival_hour           : int32      | sample: 1
next_day_arrival       : int64      | sample: 1
duration_mins          : int64      | sample: 170
stops_clean            : int64      | sample: 0
Price                  : int64      | sample: 3897
Revenue                : int64      | sample: 3897

In [29]:
# ── Export clean dataset ────────────────────────────────
df.to_csv('/data/flights_processed.csv', index=False)

print("=" * 55)
print("CLEANING COMPLETE — SUMMARY")
print("=" * 55)
print(f"Total rows saved     : {len(df):,}")
print(f"Total columns        : {df.shape[1]}")
print(f"Duration range       : {df['duration_mins'].min()}"
      f"–{df['duration_mins'].max()} mins")
print(f"Stop values          : {sorted(df['stops_clean'].dropna().unique().tolist())}")
print(f"Month range          : {df['journey_month'].min()}"
      f"–{df['journey_month'].max()}")
print(f"Dep hour range       : {df['dep_hour'].min()}"
      f"–{df['dep_hour'].max()}")
print()
print("✅ flights_processed.csv saved to data/ folder")

OSError: Cannot save file into a non-existent directory: '/data'

In [34]:
import os

# ── Hard set correct project root ───────────────────────
PROJECT_ROOT = '/Users/apple/Documents/GitHub/airline-revenue-management'

# Your folders (match exact capitalisation from your machine)
DATA_DIR     = os.path.join(PROJECT_ROOT, 'Data')
SCREENSHOTS  = os.path.join(PROJECT_ROOT, 'Screenshots', 'python')
SQL_DIR      = os.path.join(PROJECT_ROOT, 'SQL')
PYTHON_DIR   = os.path.join(PROJECT_ROOT, 'Python')

# Create screenshots/python subfolder if missing
os.makedirs(SCREENSHOTS, exist_ok=True)

print("=" * 55)
print("PATH CONFIGURATION")
print("=" * 55)
print(f"Project root  : {PROJECT_ROOT}")
print(f"Data folder   : {DATA_DIR}")
print(f"Screenshots   : {SCREENSHOTS}")
print()

# ── Check what is in Data/ folder ───────────────────────
print("Contents of Data/ folder:")
if os.path.exists(DATA_DIR):
    for f in os.listdir(DATA_DIR):
        print(f"  {f}")
else:
    print("  Data/ folder not found")

# ── Check root level CSV ─────────────────────────────────
root_csv = os.path.join(PROJECT_ROOT, 'flights_clean.csv')
if os.path.exists(root_csv):
    print()
    print("⚠️  flights_clean.csv found at ROOT level — not inside Data/")
    print(f"   Location : {root_csv}")

=======================================================
PATH CONFIGURATION
=======================================================
Project root  : /Users/apple/Documents/GitHub/airline-revenue-management
Data folder   : /Users/apple/Documents/GitHub/airline-revenue-management/Data
Screenshots   : /Users/apple/Documents/GitHub/airline-revenue-management/Screenshots/python

Contents of Data/ folder:
  .DS_Store
  Data_Collection_Dataset.pdf

⚠️  flights_clean.csv found at ROOT level — not inside Data/
   Location : /Users/apple/Documents/GitHub/airline-revenue-management/flights_clean.csv

In [35]:
import shutil

# Source — currently at root level
source = os.path.join(PROJECT_ROOT, 'flights_clean.csv')

# Destination — inside Data/ folder
destination = os.path.join(DATA_DIR, 'flights_clean.csv')

# Move it
if os.path.exists(source):
    shutil.move(source, destination)
    print(f"✅ Moved flights_clean.csv into Data/ folder")
    print(f"   From : {source}")
    print(f"   To   : {destination}")
else:
    print(f"✅ flights_clean.csv already in Data/ folder")

# Confirm
print()
print("Data/ folder now contains:")
for f in os.listdir(DATA_DIR):
    print(f"  {f}")

✅ Moved flights_clean.csv into Data/ folder
   From : /Users/apple/Documents/GitHub/airline-revenue-management/flights_clean.csv
   To   : /Users/apple/Documents/GitHub/airline-revenue-management/Data/flights_clean.csv

Data/ folder now contains:
  .DS_Store
  Data_Collection_Dataset.pdf
  flights_clean.csv

In [36]:
# ── Load clean CSV ───────────────────────────────────────
csv_path = os.path.join(DATA_DIR, 'flights_clean.csv')
df = pd.read_csv(csv_path)
print(f"✅ Loaded : {df.shape[0]:,} rows × {df.shape[1]} columns")
print()

# ── Save processed CSV ───────────────────────────────────
processed_path = os.path.join(DATA_DIR, 'flights_processed.csv')
df.to_csv(processed_path, index=False)
print(f"✅ Saved  : {processed_path}")
print(f"✅ Rows   : {len(df):,}")
print(f"✅ Cols   : {df.shape[1]}")

✅ Loaded : 10,683 rows × 12 columns

✅ Saved  : /Users/apple/Documents/GitHub/airline-revenue-management/Data/flights_processed.csv
✅ Rows   : 10,683
✅ Cols   : 12

✅ Ready — 10,683 rows × 12 columns